cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'imagemagick'
brew 'vim'
brew 'heroku-toolbelt'
brew 'tmux'
brew 'the_silver_searcher'
brew 'postgresql'
brew 'phantomjs'
brew 'awscli'
brew 'chruby'
brew 'pgcli'
