ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

alias em=ember
alias be="bundle exec"
alias bower="noglob bower"
alias pdflatex="mkdir -p build; pdflatex -output-directory build"
alias vi=vim

DISABLE_CORRECTION="true"

DISABLE_AUTO_UPDATE="true" #Stop breaking my shit!

plugins=(docker git gem rails ruby heroku bundler brew pass npm)

source $ZSH/oh-my-zsh.sh
[ -f dnvm.sh ] &&  source dnvm.sh

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

PATH=$PATH:/usr/local/share/npm/bin

. "/usr/local/bin/chnode"
NODES+=(/usr/local/Cellar/node012/*)
NODES+=(/usr/local/Cellar/node/*)

eval "$(dinghy shellinit)"

export EDITOR=vim
export PATH="/usr/local/sbin:$PATH"
