ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

alias be="bundle exec"
alias bower="noglob bower"
alias vi=vim
alias dn=dotnet
alias dotfiles="cd ~/.dotfiles"
alias mux=tmuxinator

DISABLE_CORRECTION="true"

plugins=(docker git brew npm tmux nvm bower chruby)

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

PATH=$PATH:/usr/local/share/npm/bin

export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

export NVM_DIR="$HOME/.nvm"

# Running on mac
if [ -x "$(command -v brew)" ]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi

# Running on linux
if [ -x "$(command -v apt-get)" ]; then
  . "$NVM_DIR/nvm.sh"
fi

export EDITOR=vim
export PATH="/usr/local/sbin:$PATH"

source $ZSH/oh-my-zsh.sh
