ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"

alias em=ember
alias ems="em s"
alias be="bundle exec"
alias bower="noglob bower"
alias vi=vim
alias rjw="rake jobs:work"
alias dotfiles="cd ~/.dotfiles"
alias nombom='npm cache clear && bower cache clean && rm -rf node_modules bower_components tmp dist && npm install && bower install'

DISABLE_CORRECTION="true"

plugins=(docker git gem rails ruby heroku bundler brew pass npm tmux nvm bower chruby)

source $ZSH/oh-my-zsh.sh

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

PATH=$PATH:/usr/local/share/npm/bin

export NVM_DIR="$HOME/.nvm"

# Running on mac
if [ -x "$(command -v brew)" ]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi

# Running on linux
if [ -x "$(command -v apt-get)" ]; then
  . "$NVM_DIR/nvm.sh"
fi

export EDITOR=vim
export PATH="/usr/local/sbin:$PATH"
